CREATE TABLE DECLINED_INVITATIONS
(
    FIRST_CODE INTEGER NOT NULL,
    SECOND_CODE INTEGER NOT NULL,
    PRIMARY KEY ( FIRST_CODE, SECOND_CODE ),
    FOREIGN KEY ( FIRST_CODE ) REFERENCES USERS( CODE ),
    FOREIGN KEY ( SECOND_CODE ) REFERENCES USERS( CODE )
)
