CREATE TABLE FRIENDS
(
    USER_CODE INTEGER NOT NULL,
    FRIEND_CODE INTEGER NOT NULL,
    PRIMARY KEY ( USER_CODE, FRIEND_CODE ),
    FOREIGN KEY ( USER_CODE ) REFERENCES USERS( CODE ),
    FOREIGN KEY ( FRIEND_CODE ) REFERENCES USERS( CODE )
)
