SELECT US_FR.NICK_NAME AS "NICK_NAME"
FROM USERS US,
     USERS US_FR,
     FRIENDS FR1,
     FRIENDS FR2

WHERE LOWER( US.NICK_NAME ) = 'quarto'
  AND US.CODE               = FR1.USER_CODE
  AND US_FR.CODE            = FR1.FRIEND_CODE
  AND FR1.FRIEND_CODE       = FR2.USER_CODE
  AND FR2.FRIEND_CODE       = US.CODE
ORDER BY US_FR.CODE
